language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coverage python-coveralls
  - sudo apt-get install libxml2-utils
  - test/schema/download_schema.sh
script:
  - coverage3 run setup.py test
after_success:
  - coveralls